apiVersion: v1
kind: Deployment
metadata:
  name: netology-ml
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5.69
        ports:
        - containerPort: 8080